Update extension update test for new versions (#247)
Update the minor-version-upgrade (aka ALTER EXTENSION UPDATE) test to
use the next version engine branch and the new source/from tags.

Signed-off-by: Jim C. Nasby nasbyj@amazon.com
Admin-override: accept @2jungkook's approval

diff --git a/.github/scripts/clone_engine_repo b/.github/scripts/clone_engine_repo
--- a/.github/scripts/clone_engine_repo
+++ b/.github/scripts/clone_engine_repo
@@ -16,12 +16,24 @@ set -e
 
 # Look for a config file and read it if it's there. Intentionally use -x
 # instead of -r so we get an error if we can't read the config file.
-if [ -x "${0}.conf" ]; then
-    . ${0}.conf
+CONFIG_FILE=${0}.conf
+if [ -r "$CONFIG_FILE" ]; then
+    echo "Sourcing config file $CONFIG_FILE"
+    . $CONFIG_FILE
+else
+    if [ -e "$CONFIG_FILE" ]; then
+        # Unlike the case below, if the file exists but isn't readable that is
+        # almost certainly not what the user is expecting, so treat it as an error.
+        echo "ERROR: config file $CONFIG_FILE is not readable"
+        exit 1
+    else
+        echo "WARNING: config file $CONNFIG_FILE not found; using defaults."
+    fi
 fi
 
 if [ "$1" == -n ]; then
     DRY_RUN=1
+    echo DRY RUN MODE
     shift
 fi
 
