Modified new singledb workflow to use setup-base-vers composite action

diff --git a/.github/composite-actions/setup-base-version/action.yml b/.github/composite-actions/setup-base-version/action.yml
--- a/.github/composite-actions/setup-base-version/action.yml
+++ b/.github/composite-actions/setup-base-version/action.yml
@@ -77,6 +77,7 @@ runs:
 
     - name: Run JDBC Upgrade Tests
       id: jdbc-upgrade-tests
+      if: ${{ inputs.migration_mode }} == 'multi-db'
       env:
         base_dir: ${{ matrix.upgrade-path.path[0] }}
       run: |
@@ -102,6 +103,30 @@ runs:
         export scheduleFile=upgrade/$base_dir/schedule
         mvn test
       shell: bash
+
+    - name: Run JDBC Upgrade Tests (Prepare) in single-db mode
+      id: jdbc-upgrade-tests-singledb
+      if: ${{ inputs.migration_mode }} == 'single-db'
+      run: |
+        cd test/JDBC/
+        export isUpgradeTestMode=false
+        export inputFilesPath=upgrade/singledb/preparation
+        for file in ./upgrade/singledb/preparation/*; do mv "$file" "${file%.*}-singledb.sql"; done;
+        mvn test
+        for filename in $(grep -v "^ignore.*\|^#.*\|^cmd.*\|^all.*\|^$" upgrade/singledb/schedule); do
+          if [[ ! ($(find input/ -name $filename"-vu-prepare.*") || $(find input/ -name $filename"-vu-verify.*")) ]]; then 
+            printf '%s\n' "ERROR: Cannot find Test file "$filename"-vu-prepare or "$filename"-vu-verify in input directory !!" >&2
+            exit 1
+          fi
+        done
+        export inputFilesPath=input
+        for filename in $(grep -v "^ignore.*\|^#.*\|^cmd.*\|^all.*\|^$" upgrade/singledb/schedule); do
+          sed -i "s/$filename[ ]*$/$filename-vu-prepare/g" upgrade/singledb/schedule
+        done
+        export scheduleFile=upgrade/singledb/schedule
+        mvn test
+      shell: bash
+
 
     - name: Install Python
       id: install-python
diff --git a/.github/workflows/singledb-version-upgrade.yml b/.github/workflows/singledb-version-upgrade.yml
--- a/.github/workflows/singledb-version-upgrade.yml
+++ b/.github/workflows/singledb-version-upgrade.yml
@@ -12,99 +12,20 @@ jobs:
 
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-
-      - name: Install Dependencies
-        id: install-dependencies
+      - name: Setup Base version ${{ env.ENGINE_BRANCH_FROM }} and run prepare tests
+        id: setup-base-version
         if: always()
-        uses: ./.github/composite-actions/install-dependencies
-
-      - name: Build Modified Postgres using ${{env.ENGINE_BRANCH_FROM}}
-        id: build-modified-postgres-old
-        if: always() && steps.install-dependencies.outcome == 'success'
-        run: |
-          cd ..
-          git clone --branch ${{env.ENGINE_BRANCH_FROM}} https://github.com/babelfish-for-postgresql/postgresql_modified_for_babelfish.git
-          cd postgresql_modified_for_babelfish
-          ./configure --prefix=$HOME/${{env.OLD_INSTALL_DIR}} --with-python PYTHON=/usr/bin/python2.7 --enable-debug CFLAGS="-ggdb" --with-libxml --with-uuid=ossp --with-icu
-          make clean
-          make -j 4 2>error.txt
-          make install
-          make check
-          cd contrib && make && sudo make install
-        shell: bash
-      
-      - name: Compile ANTLR
-        id: compile-antlr
-        if: always() && steps.build-modified-postgres-old.outcome == 'success'
-        uses: ./.github/composite-actions/compile-antlr
+        uses: ./.github/composite-actions/setup-base-version
         with:
-          install_dir: ${{env.OLD_INSTALL_DIR}}
+          engine_branch: ${{ env.ENGINE_BRANCH_FROM }}
+          extension_branch: ${{ env.EXTENSION_BRANCH_FROM }}
+          install_dir: ${{ env.OLD_INSTALL_DIR }}
+          migration_mode: 'single-db'
 
-      - uses: actions/checkout@v2
-        with:
-          repository: babelfish-for-postgresql/babelfish_extensions
-          ref: ${{env.EXTENSION_BRANCH_FROM}}
-      
-      - name: Build Extensions using ${{env.EXTENSION_BRANCH_FROM}}
-        id: build-extensions-old
-        if: always() && steps.compile-antlr.outcome == 'success'
-        run: |
-          export PG_CONFIG=~/${{env.OLD_INSTALL_DIR}}/bin/pg_config
-          export PG_SRC=~/work/babelfish_extensions/postgresql_modified_for_babelfish
-          export cmake=$(which cmake)
-          cd contrib/babelfishpg_money
-          make && make install
-          cd ../babelfishpg_common
-          make && make install
-          cd ../babelfishpg_tds
-          make && make install
-          cd ../babelfishpg_tsql
-          make && make install
-      
-      - name: Install Extensions using ${{env.EXTENSION_BRANCH_FROM}}
-        id: install-extensions-old
-        if: always() && steps.build-extensions-old.outcome == 'success'
-        run: |
-          cd ~
-          export PATH=/opt/mssql-tools/bin:$PATH
-          ~/${{env.OLD_INSTALL_DIR}}/bin/initdb -D ~/${{env.OLD_INSTALL_DIR}}/data
-          ~/${{env.OLD_INSTALL_DIR}}/bin/pg_ctl -D ~/${{env.OLD_INSTALL_DIR}}/data -l logfile13 start
-          cd ${{env.OLD_INSTALL_DIR}}/data
-          sudo sed -i "s/#listen_addresses = 'localhost'/listen_addresses = '*'/g" postgresql.conf
-          sudo sed -i "s/#shared_preload_libraries = ''/shared_preload_libraries = 'babelfishpg_tds'/g" postgresql.conf
-          ipaddress=$(ifconfig eth0 | grep 'inet ' | cut -d: -f2 | awk '{ print $2}')
-          sudo echo "host    all             all             $ipaddress/32            trust" >> pg_hba.conf
-          ~/${{env.OLD_INSTALL_DIR}}/bin/pg_ctl -D ~/${{env.OLD_INSTALL_DIR}}/data -l logfile13 restart
-          cd ~/work/babelfish_extensions/babelfish_extensions/
-          sudo ~/${{env.OLD_INSTALL_DIR}}/bin/psql -d postgres -U runner -v user="jdbc_user" -v db="jdbc_testdb" -f .github/scripts/create_extension.sql
-          sqlcmd -S localhost -U jdbc_user -P 12345678 -Q "SELECT @@version GO"
-        shell: bash
-
-      - uses: actions/checkout@v2
-      
-      - name: Run JDBC Upgrade Tests (Prepare)
-        id: jdbc-upgrade-tests-prepare
-        if: always() && steps.install-extensions-old.outcome == 'success'
-        run: |
-          cd test/JDBC/
-          export isUpgradeTestMode=false
-          export inputFilesPath=input
-          for filename in $(grep -v "^ignore.*\|^#.*\|^cmd.*\|^all.*\|^$" upgrade/singledb/schedule); do
-            sed -i "s/$filename[ ]*$/$filename-vu-prepare/g" upgrade/singledb/schedule
-          done
-          for filename in $(grep -v "^ignore.*\|^#.*\|^cmd.*\|^all.*\|^$" upgrade/singledb/schedule); do
-            mv input/$filename.sql input/$filename-singledb.sql
-            sed -i "s/$filename[ ]*$/$filename-singledb/g" upgrade/singledb/schedule
-          done
-          export scheduleFile=upgrade/singledb/schedule
-          cat upgrade/singledb/schedule
-          mvn test
-        shell: bash
 
       - name: Build Modified Postgres using latest version
         id: build-modified-postgres-new
-        if: always() && steps.jdbc-upgrade-tests-prepare.outcome == 'success'
+        if: always() && steps.setup-base-version.outcome == 'success'
         uses: ./.github/composite-actions/build-modified-postgres
         with:
           install_dir: ${{env.NEW_INSTALL_DIR}}
@@ -145,16 +66,21 @@ jobs:
         run: |
           cd test/JDBC/
           export isUpgradeTestMode=false
+          export inputFilesPath=upgrade/singledb/verification_cleanup
+          for file in ./upgrade/singledb/verification_cleanup/*; do mv "$file" "${file%.*}-singledb.sql"; done;
+          mvn test
+
+          for filename in $(grep -v "^ignore.*\|^#.*\|^cmd.*\|^all.*\|^$" upgrade/singledb/schedule); do
+            if [[ ! ($(find input/ -name $filename"-vu-prepare.*") || $(find input/ -name $filename"-vu-verify.*")) ]]; then 
+              printf '%s\n' "ERROR: Cannot find Test file "$filename"-vu-prepare or "$filename"-vu-verify in input directory !!" >&2
+              exit 1
+            fi
+          done
           export inputFilesPath=input
           for filename in $(grep -v "^ignore.*\|^#.*\|^cmd.*\|^all.*\|^$" upgrade/singledb/schedule); do
             sed -i "s/$filename[ ]*$/$filename-vu-verify\\n$filename-vu-cleanup/g" upgrade/singledb/schedule
           done
-          for filename in $(grep -v "^ignore.*\|^#.*\|^cmd.*\|^all.*\|^$" upgrade/singledb/schedule); do
-            mv input/$filename.sql input/$filename-singledb.sql
-            sed -i "s/$filename[ ]*$/$filename-singledb/g" upgrade/singledb/schedule
-          done
           export scheduleFile=upgrade/singledb/schedule
-          cat upgrade/singledb/schedule
           mvn test
         shell: bash
 
@@ -203,10 +129,3 @@ jobs:
         with:
           name: output-diff.diff
           path: test/JDBC/Info/output-diff.diff
-
-      
-      
-
-
-
-      
