Update error condition
Signed-off-by: Shameem Ahmed <shameemahmed20apr2000@gmail.com>

diff --git a/.github/workflows/unit-tests.yml b/.github/workflows/unit-tests.yml
--- a/.github/workflows/unit-tests.yml
+++ b/.github/workflows/unit-tests.yml
@@ -45,8 +45,13 @@ jobs:
         if: always() && steps.build-babelfishpg_unit.outcome == 'success'
         timeout-minutes: 60
         run: |
-          set -e
-          echo | sudo ~/psql/bin/psql -d jdbc_testdb -U jdbc_user -f .github/scripts/unit_tests.sql
+          echo | sudo ~/psql/bin/psql -d jdbc_testdb -U jdbc_user -f .github/scripts/unit_tests.sql -o ~/psql/output.out
+          count=$(awk -F '|' '$2 ~ /fail/'  ~/psql/output.out  | wc -l)
+          if [ "$count" -gt 0 ]; then
+            echo "Tests failed: $count"
+            exit 1
+          fi
+          rm -rf ~/psql/output.out
 
       - name: Upload Log
         if: always() && steps.unit.outcome == 'failure'
